package client.command;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class CommandTranslator {
    private static final Map<String, String> TRANSLATIONS;

    static {
        Map<String, String> m = new HashMap<>();
        // General commands
        m.put("Set world boss drop rate.", "Establece la tasa de drop de jefes del mundo.");
        m.put("Warp to a different world.", "Teletransportarse a un mundo diferente.");
        m.put("Set availability of coupons in Cash Shop.", "Establece la disponibilidad de cupones en la Tienda Cash.");
        m.put("Spawn player NPCs of all existing players.", "Genera NPCs de jugador para todos los jugadores existentes.");
        m.put("Shut down the server.", "Apagar el servidor.");
        m.put("Set GM level of a player.", "Establece el nivel GM de un jugador.");
        m.put("Remove a world.", "Eliminar un mundo.");
        m.put("Remove channel from a world.", "Eliminar un canal de un mundo.");
        m.put("Add a new world.", "Agregar un nuevo mundo.");
        m.put("Add a new channel to a world.", "Agregar un nuevo canal a un mundo.");
        m.put("Save all characters.", "Guardar todos los personajes.");
        m.put("Show all players on the map.", "Mostrar todos los jugadores en el mapa.");
        m.put("Show account name of an online player.", "Mostrar el nombre de cuenta de un jugador en línea.");
        m.put("Remove all player NPCs.", "Eliminar todos los NPCs de jugador.");
        m.put("Runs devtest.js. Developer utility - test stuff without restarting the server.", "Ejecuta devtest.js. Utilidad de desarrollador: probar cosas sin reiniciar el servidor.");
        m.put("Spawn Zakum on your location.", "Generar Zakum en tu ubicación.");
        m.put("Disconnect all players (online or logged in).", "Desconectar a todos los jugadores (en línea o conectados).");
        m.put("Set world travel rate.", "Establecer la tasa de viaje del mundo.");
        m.put("Clear cache of a quest.", "Limpiar la caché de una misión.");
        m.put("Set stats of all equips in inventory.", "Establecer las estadísticas de todos los equipamientos en el inventario.");
        m.put("Clear all quest cache.", "Limpiar toda la caché de misiones.");
        m.put("Set scrolling server message.", "Establecer el mensaje desplazable del servidor.");
        m.put("Set world quest rate.", "Establecer la tasa de misiones del mundo.");
        m.put("Spawn an item with custom stats.", "Generar un objeto con estadísticas personalizadas.");
        m.put("Remove a permanent NPC on the map.", "Eliminar un NPC permanente del mapa.");
        m.put("Spawn a permanent NPC on your location.", "Generar un NPC permanente en tu ubicación.");
        m.put("Remove all permanent mobs of the same type on the map.", "Eliminar todos los mobs permanentes del mismo tipo en el mapa.");
        m.put("Spawn a permanent mob on your location.", "Generar un mob permanente en tu ubicación.");
        m.put("Show online sessions.", "Mostrar sesiones en línea.");
        m.put("Remove a \"lv 200\" player NPC.", "Eliminar un NPC de jugador 'nivel 200'.");
        m.put("Toggle show received packets in console.", "Activar/desactivar mostrar paquetes recibidos en la consola.");
        m.put("Spawn a player NPC of an online player.", "Generar un NPC de jugador de un jugador en línea.");
        m.put("Toggle show move life in console.", "Activar/desactivar mostrar movimientos de vida en la consola.");
        m.put("Spawn Pink Bean on your location.", "Generar Pink Bean en tu ubicación.");
        m.put("Store value in an array, for testing.", "Almacenar un valor en un arreglo, para pruebas.");
        m.put("Spawn Pianus (R) on your location.", "Generar Pianus (R) en tu ubicación.");
        m.put("Show IP of all players.", "Mostrar la IP de todos los jugadores.");
        m.put("Spawn Papulatus on your location.", "Generar Papulatus en tu ubicación.");
        m.put("Show a debug message.", "Mostrar un mensaje de depuración.");
        m.put("Set world meso rate.", "Establecer la tasa de mesos del mundo.");
        m.put("Loot all drops on the map.", "Recolectar todas las gotas del mapa.");
        m.put("Spawn Horntail on your location.", "Generar Horntail en tu ubicación.");
        m.put("Set fishing rate.", "Establecer la tasa de pesca.");
        m.put("Set world exp rate.", "Establecer la tasa de experiencia del mundo.");
        m.put("Set world drop rate.", "Establecer la tasa de drops del mundo.");
        m.put("Spawn Cake boss with specified HP.", "Generar el jefe Cake con HP especificado.");
        m.put("Kill a player.", "Matar a un jugador.");
        m.put("Kill all mobs in the map.", "Matar todos los mobs en el mapa.");
        m.put("Show all players in the map.", "Mostrar todos los jugadores en el mapa.");
        m.put("Unban a player.", "Desbanear a un jugador.");
        m.put("Show all characters being ignored in auto-ban alerts.", "Mostrar todos los personajes ignorados en alertas de autobaneo.");
        m.put("Toggle ignore a character from auto-ban alerts.", "Alternar ignorar a un personaje en alertas de autobaneo.");
        m.put("Toggle enable/disable a coupon.", "Alternar habilitar/deshabilitar un cupón.");
        m.put("Nearly kill a player.", "Casi matar a un jugador.");
        m.put("Set HP/MP of a player.", "Establecer HP/MP de un jugador.");
        m.put("Set timer on all players in current map.", "Establecer temporizador en todos los jugadores del mapa actual.");
        m.put("Heal all HP/MP of a player.", "Curar todo el HP/MP de un jugador.");
        m.put("Set timer on a player in current map.", "Establecer temporizador en un jugador del mapa actual.");
        m.put("Heal all HP/MP of all players in the map.", "Curar todo el HP/MP de todos los jugadores en el mapa.");
        m.put("Set a server wide timer.", "Establecer un temporizador a nivel de servidor.");
        m.put("Stop ongoing \"classic\" event.", "Detener el evento clásico en curso.");
        m.put("Change hair of a player.", "Cambiar el cabello de un jugador.");
        m.put("Start a \"classic\" event on current map.", "Iniciar un evento clásico en el mapa actual.");
        m.put("Give vote points to a player.", "Dar puntos de voto a un jugador.");
        m.put("Start an event on current map.", "Iniciar un evento en el mapa actual.");
        m.put("Give reward points to a player.", "Dar puntos de recompensa a un jugador.");
        m.put("Spawn mob(s) on your location.", "Generar mob(s) en tu ubicación.");
        m.put("Give NX to a player.", "Dar NX a un jugador.");
        m.put("Drop all seeds inside Henesys PQ.", "Soltar todas las semillas dentro de Henesys PQ.");
        m.put("Send a RIP notice.", "Enviar un aviso RIP.");
        m.put("Give mesos to a player.", "Dar mesos a un jugador.");
        m.put("Reload popup shops and NPC shops.", "Recargar tiendas emergentes y tiendas NPC.");
        m.put("Enable/disable fly feature.", "Habilitar/deshabilitar la función volar.");
        m.put("Reload all portal scripts.", "Recargar todos los scripts de portales.");
        m.put("Set new fame value of a player.", "Establecer un nuevo valor de fama de un jugador.");
        m.put("Reload the map.", "Recargar el mapa.");
        m.put("Change face of a player.", "Cambiar la cara de un jugador.");
        m.put("Reload all event data.", "Recargar todos los datos de eventos.");
        m.put("Show all ongoing boss expeditions.", "Mostrar todas las expediciones de jefes en curso.");
        m.put("Reload all drop data.", "Recargar todos los datos de drops.");
        m.put("Close entry for ongoing event.", "Cerrar inscripciones para el evento en curso.");
        m.put("Start a quest.", "Iniciar una misión.");
        m.put("Put a debuff on all nearby players.", "Aplicar un debuff a todos los jugadores cercanos.");
        m.put("Reset a completed quest.", "Reiniciar una misión completada.");
        m.put("Close a portal.", "Cerrar un portal.");
        m.put("Complete an active quest.", "Completar una misión activa.");
        m.put("Show stats and damage of a player.", "Mostrar estadísticas y daño de un jugador.");
        m.put("Show current position and foothold.", "Mostrar posición y foothold actual.");
        m.put("Toggle white GM chat.", "Alternar chat blanco de GM.");
        m.put("Ban a player.", "Banear a un jugador.");
        m.put("Handle synthesized packets from file, and handle them as if sent from a client", "Procesar paquetes sintetizados desde archivo como si fueran enviados por un cliente");
        m.put("Play a song.", "Reproducir una canción.");
        m.put("Open a portal on the map.", "Abrir un portal en el mapa.");
        m.put("Show all characters being monitored for packet logging", "Mostrar todos los personajes monitoreados para registro de paquetes");
        m.put("Show all online players.", "Mostrar todos los jugadores en línea.");
        m.put("Toggle monitored packet logging of a character.", "Alternar registro de paquetes monitoreados de un personaje.");
        m.put("Set base HP/MP of a player.", "Establecer HP/MP base de un jugador.");
        m.put("Spawn an NPC on your location.", "Generar un NPC en tu ubicación.");
        m.put("Set dojo energy to max value.", "Establecer la energía del dojo al máximo.");
        m.put("Send a blue message to everyone on the server.", "Enviar un mensaje azul a todos en el servidor.");
        m.put("Kill all players in the map.", "Matar a todos los jugadores en el mapa.");
        m.put("Set sky background to black.", "Poner el fondo del cielo en negro.");
        m.put("Search in handbook.", "Buscar en la enciclopedia.");
        m.put("Clear saved locations for a player.", "Limpiar ubicaciones guardadas de un jugador.");
        m.put("Max out all job skills.", "Maximizar todas las habilidades de trabajo.");
        m.put("Bomb a player, dealing damage.", "Bomba a un jugador, causando daño.");
        m.put("Toggle mute players in the map.", "Alternar silenciar jugadores en el mapa.");
        m.put("Hide from players.", "Ocultarse de los jugadores.");
        m.put("Clear drops by player.", "Limpiar drops por jugador.");
        m.put("Loots all items that belong to you.", "Recoge todos los objetos que te pertenecen.");
        m.put("Show info about objects on current map.", "Mostrar información sobre objetos en el mapa actual.");
        m.put("Activate all useful buffs.", "Activar todos los buffs útiles.");
        m.put("Give GM buffs to the whole map.", "Dar buffs de GM a todo el mapa.");
        m.put("Set your level, one by one.", "Establecer tu nivel, uno por uno.");
        m.put("Disconnect a player.", "Desconectar a un jugador.");
        m.put("Activate GM buffs on self.", "Activar buffs de GM en uno mismo.");
        m.put("Fully heal your HP/MP.", "Curar completamente tu HP/MP.");
        m.put("Set your level.", "Establecer tu nivel.");
        m.put("Warp all characters on current map to a new map.", "Teletransportar a todos los personajes del mapa actual a un nuevo mapa.");
        m.put("Clear all items in an inventory tab.", "Eliminar todos los objetos en una pestaña de inventario.");
        m.put("Activate a buff.", "Activar un buff.");
        m.put("Show HP of bosses on current map.", "Mostrar HP de los jefes en el mapa actual.");
        m.put("Change job of a player.", "Cambiar el trabajo de un jugador.");
        m.put("Open the GM shop.", "Abrir la tienda GM.");
        m.put("Show gachapon rewards.", "Mostrar recompensas de gachapon.");
        m.put("Warp to a map.", "Teletransportarse a un mapa.");
        m.put("Show HP of mobs on current map.", "Mostrar HP de mobs en el mapa actual.");
        m.put("Set available AP.", "Establecer AP disponible.");
        m.put("Move a player to the jail.", "Mover a un jugador a la cárcel.");
        m.put("Warp to a player.", "Teletransportarse a un jugador.");
        m.put("Spawn an item onto the ground.", "Generar un objeto en el suelo.");
        m.put("Set amount of inventory slots in all tabs.", "Establecer la cantidad de ranuras de inventario en todas las pestañas.");
        m.put("Warp all nearby players to a new map.", "Teletransportar a todos los jugadores cercanos a un nuevo mapa.");
        m.put("Warp to a predefined map.", "Teletransportarse a un mapa predefinido.");
        m.put("Spawn an item into your inventory.", "Generar un objeto en tu inventario.");
        m.put("Move a player to your location.", "Mover a un jugador a tu ubicación.");
        m.put("Apply a mob skill to all mobs on the map. Args: <mob skill id> <skill level>", "Aplicar una habilidad de mob a todos los mobs del mapa. Args: <id habilidad mob> <nivel de habilidad>");
        m.put("Search String.wz.", "Buscar en String.wz.");
        m.put("Set available SP.", "Establecer SP disponible.");
        m.put("Free a player from jail.", "Liberar a un jugador de la cárcel.");
        m.put("Show what items drop from a mob.", "Mostrar qué objetos suelta un mob.");
        m.put("Set all skill levels to 0.", "Poner todos los niveles de habilidades en 0.");
        m.put("Show what drops an item.", "Mostrar qué suelta un objeto.");
        m.put("Recharge and refill all USE items.", "Recargar y rellenar todos los objetos de tipo USE.");
        m.put("Set all primary stats to new value.", "Establecer todos los atributos primarios a un nuevo valor.");
        m.put("Unbug self.", "Desbuguearse.");
        m.put("Toggle Hide.", "Alternar ocultarse.");
        m.put("Max out all character stats.", "Maximizar todas las estadísticas del personaje.");
        m.put("Enable PIC code by resetting the cooldown.", "Habilitar código PIC reiniciando el tiempo de reutilización.");
        m.put("Change language settings.", "Cambiar la configuración de idioma.");
        m.put("Check drop limit of current map.", "Comprobar el límite de drops del mapa actual.");
        m.put("Dispose to fix NPC chat.", "Disposear para arreglar chat de NPC.");
        m.put("Send a message to the game masters.", "Enviar un mensaje a los maestros del juego.");
        m.put("Show levels of all equipped items.", "Mostrar niveles de todos los objetos equipados.");
        m.put("Join active event.", "Unirse al evento activo.");
        m.put("Show available commands.", "Mostrar comandos disponibles.");
        m.put("Leave active event.", "Salir del evento activo.");
        m.put("Claim ownership of the current map.", "Reclamar la propiedad del mapa actual.");
        m.put("Warp to the PQ lobby.", "Teletransportarse al lobby del PQ.");
        m.put("Show your rates.", "Mostrar tus tasas.");
        m.put("Send in a bug report.", "Enviar un informe de error.");
        m.put("Show player rankings.", "Mostrar clasificación de jugadores.");
        m.put("Show credits. These people made the server possible.", "Mostrar créditos. Estas personas hicieron posible el servidor.");
        m.put("Show point total.", "Mostrar total de puntos.");
        m.put("Show all world/character rates.", "Mostrar todas las tasas del mundo/personaje.");
        m.put("Assign AP into INT.", "Asignar AP a INT.");
        m.put("Assign AP into DEX.", "Asignar AP a DEX.");
        m.put("Show current server time.", "Mostrar la hora actual del servidor.");
        m.put("Assign AP into STR.", "Asignar AP a STR.");
        m.put("Show server online time.", "Mostrar tiempo de actividad del servidor.");
        m.put("Assign AP into LUK.", "Asignar AP a LUK.");
        m.put("Toggle enable/disable all exp gain.", "Alternar habilitar/deshabilitar toda la ganancia de experiencia.");

        TRANSLATIONS = Collections.unmodifiableMap(m);
    }

    private CommandTranslator() {
    }

    public static String translate(String english) {
        if (english == null) return null;
        String t = TRANSLATIONS.get(english);
        return t != null ? t : english;
    }
}
